<?php
	class CEMVillageSurveyFields{
		public function getFields($code){
			$fields = array(
				'_URI' => '_URI',
				'_PARENT_AURI' => '_PARENT_AURI',
				'VILLAGE_CONTACT1_CEM305A_VIL_MBER_CONTACT' => 'VILLAGE_CONTACT1_CEM305A_VIL_MBER_CONTACT',
				'VILLAGE_CONTACT1_CEM305B_VIL_MBER_LANGUAGE' => 'VILLAGE_CONTACT1_CEM305B_VIL_MBER_LANGUAGE',
				'VILLAGE_CONTACT1_CEM305B_VIL_MBER_LANGUAGE_OTHER' => 'VILLAGE_CONTACT1_CEM305B_VIL_MBER_LANGUAGE_OTHER',
				'VILLAGE_CONTACT2_CEM306A_VIL_MBER_CONTACT' => 'VILLAGE_CONTACT2_CEM306A_VIL_MBER_CONTACT',
				'VILLAGE_CONTACT2_CEM306B_VIL_MBER_LANGUAGE' => 'VILLAGE_CONTACT2_CEM306B_VIL_MBER_LANGUAGE',
				'VILLAGE_CONTACT2_CEM306B_VIL_MBER_LANGUAGE_OTHER' => 'VILLAGE_CONTACT2_CEM306B_VIL_MBER_LANGUAGE_OTHER',
				'VILLAGE_CONTACT3_CEM307A_VIL_MBER_CONTACT' => 'VILLAGE_CONTACT3_CEM307A_VIL_MBER_CONTACT',
				'VILLAGE_CONTACT3_CEM307B_VIL_MBER_LANGUAGE' => 'VILLAGE_CONTACT3_CEM307B_VIL_MBER_LANGUAGE',
				'VILLAGE_CONTACT3_CEM307B_VIL_MBER_LANGUAGE_OTHER' => 'VILLAGE_CONTACT3_CEM307B_VIL_MBER_LANGUAGE_OTHER',
				'VILLAGE_CONTACT4_CEM308A_VIL_MBER_CONTACT' => 'VILLAGE_CONTACT4_CEM308A_VIL_MBER_CONTACT',
				'VILLAGE_CONTACT4_CEM308B_VIL_MBER_LANGUAGE' => 'VILLAGE_CONTACT4_CEM308B_VIL_MBER_LANGUAGE',
				'VILLAGE_CONTACT4_CEM308B_VIL_MBER_LANGUAGE_OTHER' => 'VILLAGE_CONTACT4_CEM308B_VIL_MBER_LANGUAGE_OTHER',
				'VILLAGE_CONTACT5_CEM309A_VIL_MBER_CONTACT' => 'VILLAGE_CONTACT5_CEM309A_VIL_MBER_CONTACT',
				'VILLAGE_CONTACT5_CEM309B_VIL_MBER_LANGUAGE' => 'VILLAGE_CONTACT5_CEM309B_VIL_MBER_LANGUAGE',
				'VILLAGE_CONTACT5_CEM309B_VIL_MBER_LANGUAGE_OTHER' => 'VILLAGE_CONTACT5_CEM309B_VIL_MBER_LANGUAGE_OTHER',
				'VILLAGE_CONTACT6_CEM310A_VIL_MBER_CONTACT' => 'VILLAGE_CONTACT6_CEM310A_VIL_MBER_CONTACT',
				'VILLAGE_CONTACT6_CEM310B_VIL_MBER_LANGUAGE' => 'VILLAGE_CONTACT6_CEM310B_VIL_MBER_LANGUAGE',
				'VILLAGE_CONTACT6_CEM310B_VIL_MBER_LANGUAGE_OTHER' => 'VILLAGE_CONTACT6_CEM310B_VIL_MBER_LANGUAGE_OTHER',
				'VILLAGE_CONTACT7_CEM311A_VIL_MBER_CONTACT' => 'VILLAGE_CONTACT7_CEM311A_VIL_MBER_CONTACT',
				'VILLAGE_CONTACT7_CEM311B_VIL_MBER_LANGUAGE' => 'VILLAGE_CONTACT7_CEM311B_VIL_MBER_LANGUAGE',
				'VILLAGE_CONTACT7_CEM311B_VIL_MBER_LANGUAGE_OTHER' => 'VILLAGE_CONTACT7_CEM311B_VIL_MBER_LANGUAGE_OTHER',
				'VILLAGE_CONTACT8_CEM312A_VIL_MBER_CONTACT' => 'VILLAGE_CONTACT8_CEM312A_VIL_MBER_CONTACT',
				'VILLAGE_CONTACT8_CEM312B_VIL_MBER_LANGUAGE' => 'VILLAGE_CONTACT8_CEM312B_VIL_MBER_LANGUAGE',
				'VILLAGE_CONTACT8_CEM312B_VIL_MBER_LANGUAGE_OTHER' => 'VILLAGE_CONTACT8_CEM312B_VIL_MBER_LANGUAGE_OTHER',
				'VILLAGE_CONTACT9_CEM313A_VIL_MBER_CONTACT' => 'VILLAGE_CONTACT9_CEM313A_VIL_MBER_CONTACT',
				'VILLAGE_CONTACT9_CEM313B_VIL_MBER_LANGUAGE' => 'VILLAGE_CONTACT9_CEM313B_VIL_MBER_LANGUAGE',
				'VILLAGE_CONTACT9_CEM313B_VIL_MBER_LANGUAGE_OTHER' => 'VILLAGE_CONTACT9_CEM313B_VIL_MBER_LANGUAGE_OTHER',
				'VILLAGE_CONTACT10_CEM314A_VIL_MBER_CONTACT' => 'VILLAGE_CONTACT10_CEM314A_VIL_MBER_CONTACT',
				'VILLAGE_CONTACT10_CEM314B_VIL_MBER_LANGUAGE' => 'VILLAGE_CONTACT10_CEM314B_VIL_MBER_LANGUAGE',
				'VILLAGE_CONTACT10_CEM314B_VIL_MBER_LANGUAGE_OTHER' => 'VILLAGE_CONTACT10_CEM314B_VIL_MBER_LANGUAGE_OTHER'
			);
			if(array_key_exists($code,$fields)){
				return $fields[$code];
			}
			else{
				return FALSE;
			}
		}
		
		public function getDBFields($code){
			$fields = array(
				'_URI' => '_uri',
				'_PARENT_AURI' => '_parent_auri',
				'VILLAGE_CONTACT1_CEM305A_VIL_MBER_CONTACT' => 'cem305a_vil_mber_contact',
				'VILLAGE_CONTACT1_CEM305B_VIL_MBER_LANGUAGE' => 'cem305b_vil_mber_language',
				'VILLAGE_CONTACT1_CEM305B_VIL_MBER_LANGUAGE_OTHER' => 'cem305b_vil_mber_language_other',
				'VILLAGE_CONTACT2_CEM306A_VIL_MBER_CONTACT' => 'cem306a_vil_mber_contact',
				'VILLAGE_CONTACT2_CEM306B_VIL_MBER_LANGUAGE' => 'cem306b_vil_mber_language',
				'VILLAGE_CONTACT2_CEM306B_VIL_MBER_LANGUAGE_OTHER' => 'cem306b_vil_mber_language_other',
				'VILLAGE_CONTACT3_CEM307A_VIL_MBER_CONTACT' => 'cem307a_vil_mber_contact',
				'VILLAGE_CONTACT3_CEM307B_VIL_MBER_LANGUAGE' => 'cem307b_vil_mber_language',
				'VILLAGE_CONTACT3_CEM307B_VIL_MBER_LANGUAGE_OTHER' => 'cem307b_vil_mber_language_other',
				'VILLAGE_CONTACT4_CEM308A_VIL_MBER_CONTACT' => 'cem308a_vil_mber_contact',
				'VILLAGE_CONTACT4_CEM308B_VIL_MBER_LANGUAGE' => 'cem308b_vil_mber_language',
				'VILLAGE_CONTACT4_CEM308B_VIL_MBER_LANGUAGE_OTHER' => 'cem308b_vil_mber_language_other',
				'VILLAGE_CONTACT5_CEM309A_VIL_MBER_CONTACT' => 'cem309a_vil_mber_contact',
				'VILLAGE_CONTACT5_CEM309B_VIL_MBER_LANGUAGE' => 'cem309b_vil_mber_language',
				'VILLAGE_CONTACT5_CEM309B_VIL_MBER_LANGUAGE_OTHER' => 'cem309b_vil_mber_language_other',
				'VILLAGE_CONTACT6_CEM310A_VIL_MBER_CONTACT' => 'cem310a_vil_mber_contact',
				'VILLAGE_CONTACT6_CEM310B_VIL_MBER_LANGUAGE' => 'cem310b_vil_mber_language',
				'VILLAGE_CONTACT6_CEM310B_VIL_MBER_LANGUAGE_OTHER' => 'cem310b_vil_mber_language_other',
				'VILLAGE_CONTACT7_CEM311A_VIL_MBER_CONTACT' => 'cem311a_vil_mber_contact',
				'VILLAGE_CONTACT7_CEM311B_VIL_MBER_LANGUAGE' => 'cem311b_vil_mber_language',
				'VILLAGE_CONTACT7_CEM311B_VIL_MBER_LANGUAGE_OTHER' => 'cem311b_vil_mber_language_other',
				'VILLAGE_CONTACT8_CEM312A_VIL_MBER_CONTACT' => 'cem312a_vil_mber_contact',
				'VILLAGE_CONTACT8_CEM312B_VIL_MBER_LANGUAGE' => 'cem312b_vil_mber_language',
				'VILLAGE_CONTACT8_CEM312B_VIL_MBER_LANGUAGE_OTHER' => 'cem312b_vil_mber_language_other',
				'VILLAGE_CONTACT9_CEM313A_VIL_MBER_CONTACT' => 'cem313a_vil_mber_contact',
				'VILLAGE_CONTACT9_CEM313B_VIL_MBER_LANGUAGE' => 'cem313b_vil_mber_language',
				'VILLAGE_CONTACT9_CEM313B_VIL_MBER_LANGUAGE_OTHER' => 'cem313b_vil_mber_language_other',
				'VILLAGE_CONTACT10_CEM314A_VIL_MBER_CONTACT' => 'cem314a_vil_mber_contact',
				'VILLAGE_CONTACT10_CEM314B_VIL_MBER_LANGUAGE' => 'cem314b_vil_mber_language',
				'VILLAGE_CONTACT10_CEM314B_VIL_MBER_LANGUAGE_OTHER' => 'cem314b_vil_mber_language_other'
			);
			if(array_key_exists($code,$fields)){
				return $fields[$code];
			}
			else{
				return FALSE;
			}
		}
	}
?>