"_URI" character varying(80) NOT NULL,
  "_CREATOR_URI_USER" character varying(80) NOT NULL,
  "_CREATION_DATE" timestamp without time zone NOT NULL,
  "_LAST_UPDATE_URI_USER" character varying(80),
  "_LAST_UPDATE_DATE" timestamp without time zone NOT NULL,
  "_MODEL_VERSION" integer,
  "_UI_VERSION" integer,
  "_IS_COMPLETE" boolean,
  "_SUBMISSION_DATE" timestamp without time zone,
  "_MARKED_AS_COMPLETE_DATE" timestamp without time zone,
  "ATTENDEESAGE_INSTRUCTION1_6" character varying(255),
  "ATTENDEESGENDER_INSTRUCTION1_5" character varying(255),
  "WATERPOINTDETAILS_VCS011_OTHER" character varying(255),
  "WATRPOINTDETALS_VIL_VCS017A" character varying(255),
  "WATRPINTDETALS_SBLOC_VCS016" character varying(255),
  "VILLAGELDER_VCS109" character varying(255),
  "VILLAGELDER_VCS108" character varying(255),
  "VILLAGELDER_VCS107" character varying(255),
  "WATRPINTDETALS_SBLOC_VCS016A" character varying(255),
  "CHALLENGES1_VCS204A" character varying(255),
  "VCS004" timestamp without time zone,
  "VCS005" timestamp without time zone,
  "VCS002" timestamp without time zone,
  "META_INSTANCE_ID" character varying(255),
  "VCS003" character varying(255),
  "S3_COMMENTS" character varying(255),
  "CHALLENGES1_VCS204B" character varying(255),
  "VCS201" integer,
  "VILLAGELDER_VCS103" character varying(255),
  "VILLAGELDER_VCS104" integer,
  "VILLAGELDER_VCS105" integer,
  "VILLAGELDER_VCS106" character varying(255),
  "VILLAGELDER_VCS101" character varying(255),
  "VILLAGELDER_VCS102" integer,
  "INSTRUCTION_INSTRUCTION1_3" character varying(255),
  "SECTION_4_THANKS" character varying(255),
  "ATTENDEESGENDER_VCS202B" integer,
  "ATTENDEESGENDER_VCS202A" integer,
  "INSTRUCTION1_4" character varying(255),
  "WATERPOINTDETAILS_VCS011" character varying(255),
  "WATERPOINTDETAILS_VCS013" character varying(255),
  "INSTRUCTION1_7" character varying(255),
  "S1_COMMENTS" character varying(255),
  "WATRPOINTDETALS_VIL_VCS017" character varying(255),
  "ATTENDEESAGE_VCS203B" integer,
  "INSTRUCTION_INSTRUCTION1_1" character varying(255),
  "VCS007" integer,
  "ATTENDEESAGE_VCS203A" integer,
  "INSTRUCTION_INSTRUCTION1_2" character varying(255),
  "VCS006" character varying(255),