"_URI" character varying(80) NOT NULL,
  "_CREATOR_URI_USER" character varying(80) NOT NULL,
  "_CREATION_DATE" timestamp without time zone NOT NULL,
  "_LAST_UPDATE_URI_USER" character varying(80),
  "_LAST_UPDATE_DATE" timestamp without time zone NOT NULL,
  "_MODEL_VERSION" integer,
  "_UI_VERSION" integer,
  "_IS_COMPLETE" boolean,
  "_SUBMISSION_DATE" timestamp without time zone,
  "_MARKED_AS_COMPLETE_DATE" timestamp without time zone,
  "INSPCTON_BASNDSTAND_S212E_BLTNUT_MISNG" character varying(255),
  "INSPCTON_TANKNDVLVE_GENERATED_TABLE_LIST_LABEL_86" character varying(255),
  "NOTE1_1" character varying(255),
  "INSPECTION_S203_TANK_IN_DISP" character varying(255),
  "INSPCTN_STCKRSNDTAGS_RESERVED_NAME_FOR_FIELD_LIST_LABELS_94" character varying(255),
  "INSPCTON_BASNDSTAND_S212A_CONCRT_CRACK" character varying(255),
  "INSPECTION_CASING_GENERATED_TABLE_LIST_LABEL_74" character varying(255),
  "INSPECTION_REFILL_NOTE2_1" character varying(255),
  "INSPECTION_CASING_S209DI_CAS_BROK_OTHERLOCTN" character varying(255),
  "S018B_SPECIAL_ACTIV_SURVEY_TYPE_OTHER" character varying(255),
  "INSPCTN_STCKRSNDTAGS_S211B_TAG_MISNG" character varying(255),
  "S_FA1" character varying(255),
  "S100_DISP_AT_WPT" character varying(255),
  "S011_PRGRM" character varying(255),
  "S107_WPT_GPS_LAT" numeric(38,10),
  "INSPCTON_TANKNDVLVE_S210D_VLV_NOTDISPNG" character varying(255),
  "INSPCTON_INSTALLTON_S107A_WPT_GPS2_LAT" numeric(38,10),
  "S002_START" timestamp without time zone,
  "INSPECTION_REFILL_S205B_FILL_TANK_WHYNOT" character varying(255),
  "S013_DISTRICT" character varying(255),
  "INSPECTION_PROBLEMS_S211_DISPPROB_STKER_TAG_PAINT" character varying(255),
  "S004_END" timestamp without time zone,
  "INSPCTON_BASNDSTAND_S212F_BLTNUT_RUST" character varying(255),
  "S009_COUNTRY" character varying(255),
  "S019A_PANEL_SURVEY" character varying(255),
  "INSPCTON_TANKNDVLVE_S210B_DISP_LEAK" character varying(255),
  "S101_WPT_NAME" character varying(255),
  "INSPECTION_PROBLEMS_RESERVED_NAME_FOR_FIELD_LIST_LABELS_69" character varying(255),
  "INSPECTION_CASING_S209G_PADLK_BROK" character varying(255),
  "S003_DEVICEID" character varying(255),
  "INSPECTION_CASING_RESERVED_NAME_FOR_FIELD_LIST_LABELS_75" character varying(255),
  "INSPECTION_CASING_S209I_PADLK_RUST" character varying(255),
  "S011_PRGRM_OTHER" character varying(255),
  "S007_SURVEYOR_ID" integer,
  "S105_DISP_SERIAL" character varying(255),
  "INSPECTION_PROBLEMS_S209_DISPPROB_CAS_PADLK" character varying(255),
  "INSPCTON_TANKNDVLVE_RESERVED_NAME_FOR_FIELD_LIST_LABELS_87" character varying(255),
  "INSPECTION_S201_DISP_GEN" character varying(255),
  "INSPECTION_S213_DTAILS_WRONG_DISP" character varying(255),
  "S107_WPT_GPS_ALT" numeric(38,10),
  "S019A_PANEL_SURVEY_OTHER" character varying(255),
  "INSPECTION_S207A_CL_SAMPL_WHYNOT" character varying(255),
  "INSPCTON_BASNDSTAND_GENERATED_TABLE_LIST_LABEL_99" character varying(255),
  "INSPCTON_BASNDSTAND_RESERVED_NAME_FOR_FIELD_LIST_LABELS_100" character varying(255),
  "INSPECTION_CASING_S209F_LID_BENT_CRACK" character varying(255),
  "INSPCTON_INSTALLTON_S215_DISP_LOCATN" character varying(255),
  "INSPCTION_VALVCHECK_NOTE2_3" character varying(255),
  "INSPCTION_VALVCHECK_NOTE2_2" character varying(255),
  "INSPECTION_CASING_S209B_CAS_CRACK" character varying(255),
  "INSPECTION_REFILL_S205A_FILL_TANK" character varying(255),
  "S110_WPT_TURBIDITY" character varying(255),
  "S100A_DISP_AT_WPT_WHYNOT" character varying(255),
  "INSPCTON_BASNDSTAND_S212D_BLTNUT_LOOSE" character varying(255),
  "INSPECTION_S207A_CL_SAMPL_WHYNOT_OTHER" character varying(255),
  "S107_WPT_GPS_ACC" numeric(38,10),
  "S019C_PANEL_SURVEY_HHOLD_ROUND_OTHER" character varying(255),
  "S006_SURVEYOR_NAME" character varying(255),
  "S005_TODAY" timestamp without time zone,
  "INSPCTN_STCKRSNDTAGS_GENERATED_TABLE_LIST_LABEL_93" character varying(255),
  "INSPECTION_S202_TANK_VOLM" character varying(255),
  "S106_DISP_BARCODE" character varying(255),
  "VIL_S017A_VIL_OTHER" character varying(255),
  "INSPCTON_INSTALLTON_S107A_WPT_GPS2_LNG" numeric(38,10),
  "INSPCTON_TANKNDVLVE_S210A_TNK_CAP_MISNG" character varying(255),
  "INSPECTION_CASING_S209E_LID_MISNG" character varying(255),
  "META_INSTANCE_ID" character varying(255),
  "VIL_S017_VIL" character varying(255),
  "INSPECTION_CASING_S209H_PADLK_MISNG" character varying(255),
  "INSPECTION_PROBLEMS_GENERATED_TABLE_LIST_LABEL_68" character varying(255),
  "S109_WPT_USABLE" character varying(255),
  "S107_WPT_GPS_LNG" numeric(38,10),
  "INSPCTON_BASNDSTAND_S212C_PST_BROK_PVC" character varying(255),
  "S015_LOCATN" character varying(255),
  "INSPCTN_STCKRSNDTAGS_S211C_STKR_MISNG_OTHER" character varying(255),
  "INSPECTION_S208_DISPPROB" character varying(255),
  "SUBLOC_S016_SUBLOC" character varying(255),
  "S018A_SURVEY_ACTIVITY" character varying(255),
  "INSPCTN_STCKRSNDTAGS_S211D_DISP_RUST_PAINT_PLNG" character varying(255),
  "WPT_S102_WPT_ID" character varying(255),
  "INSPECTION_S207_CL_SAMPL" character varying(255),
  "INSPECTION_S206_CL_DISPENSED" character varying(255),
  "INSPCTN_STCKRSNDTAGS_S211A_STKER_MISNG_INSTRN" character varying(255),
  "NOTE3_1" character varying(255),
  "INSPECTION_S205_CL_LEVEL" character varying(255),
  "INSPECTION_PROBLEMS_S210_DISPPROB_TNK_VLV" character varying(255),
  "INSPECTION_CASING_S209C_CAS_HING_BROK" character varying(255),
  "INSPCTON_TANKNDVLVE_S210C_VLV_BROK" character varying(255),
  "INSPCTON_INSTALLTON_S107A_WPT_GPS2_ACC" numeric(38,10),
  "INSPCTON_INSTALLTON_S216_DISP_FACING_WPT" character varying(255),
  "INSPECTION_S_FA2" character varying(255),
  "INSPECTION_CASING_S209A_CAS_BROK_SAG" character varying(255),
  "INSPCTON_TANKNDVLVE_S210E_VLV_MISNG" character varying(255),
  "S018B_SPECIAL_ACTIV_SURVEY_TYPE" character varying(255),
  "INSPECTION_CASING_S209D_CAS_LOKHOLE_BROK" character varying(255),
  "S108_SEASON" character varying(255),
  "INSPECTION_S204_CL_IN_TANK" character varying(255),
  "S019B_PANEL_SURVEY_HHOLD" character varying(255),
  "INSPECTION_PROBLEMS_S212_DISPPROB_BS_PVC_STND_BLT_NUT" character varying(255),
  "S103_WPT_HUB" character varying(255),
  "S014_DIVISN" character varying(255),
  "SUBLOC_S016A_SUBLOC_OTHER" character varying(255),
  "INSPECTION_S214_SUSPCT_VNDLSM" character varying(255),
  "WPT_S102A_WPT_ID_OTHER" character varying(255),
  "S109A_WPT_USABLE_WHYNOT_OTHER" character varying(255),
  "S012_COUNTY" character varying(255),
  "INSPCTON_BASNDSTAND_S212B_PST_BROK_METAL" character varying(255),
  "INSPCTON_INSTALLTON_S107A_WPT_GPS2_ALT" numeric(38,10),