"_URI" character varying(80) NOT NULL,
  "_CREATOR_URI_USER" character varying(80) NOT NULL,
  "_CREATION_DATE" timestamp without time zone NOT NULL,
  "_LAST_UPDATE_URI_USER" character varying(80),
  "_LAST_UPDATE_DATE" timestamp without time zone NOT NULL,
  "_MODEL_VERSION" integer,
  "_UI_VERSION" integer,
  "_IS_COMPLETE" boolean,
  "_SUBMISSION_DATE" timestamp without time zone,
  "_MARKED_AS_COMPLETE_DATE" timestamp without time zone,
  "ADMIN_SSM019" character varying(255),
  "ADMIN_SSM016" character varying(255),
  "META_INSTANCE_ID" character varying(255),
  "ADMIN_SSM020" integer,
  "ADMIN_SSM016_OTHER" character varying(255),
  "ADMIN_SSM011" character varying(255),
  "ADMIN_SSM014" character varying(255),
  "ADMIN_SSM015" character varying(255),
  "ADMIN_SSM012" character varying(255),
  "ADMIN_SSM013" character varying(255),
  "SSM006" character varying(255),
  "SSM005" timestamp without time zone,
  "ADMIN_SSM011_OTHER" character varying(255),
  "ADMIN_S1_COMMENTS" character varying(255),
  "SSM007" integer,
  "INSTRUCTION_INSTRUCTION1_6" character varying(255),
  "INSTRUCTION1_7" character varying(255),
  "SECTION_3_THANKS" character varying(255),
  "SSM002" timestamp without time zone,
  "S2_COMMENTS" character varying(255),
  "SSM004" timestamp without time zone,
  "INSTRUCTION_INSTRUCTION1_1" character varying(255),
  "SSM003" character varying(255),
  "INSTRUCTION_INSTRUCTION1_2" character varying(255),